In [2]:
# DAV Experiment 1 - NumPy and Pandas

import numpy as np
import pandas as pd

print("========== NUMPY ==========")

nums = np.array([10, 20, 30, 40, 50])
print("My array:", nums)


========== NUMPY ==========
Array: [10 20 30 40 50]


In [3]:
# Checking some basic array details
print("Shape:", nums.shape)
print("Dimensions:", nums.ndim)
print("Size:", nums.size)
print("Data type:", nums.dtype)


Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


In [4]:
# Lets see indexing and slicing
print("First value:", nums[0])
print("Last value:", nums[-1])
print("Middle part:", nums[1:4])


First element: 10
Last element: 50
Slicing: [20 30 40]


In [5]:
# Small array operations
other = np.array([1, 2, 3, 4, 5])
print("Addition:", nums + other)
print("Multiplication:", nums * other)
print("Subtraction:", nums - other)


Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]


In [6]:
# Some math functions
print("Square:", np.square(nums))
print("Square root:", np.sqrt(nums))


Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Square: [ 100  400  900 1600 2500]


In [7]:
# A few statistical functions
print("Mean:", np.mean(nums))
print("Sum:", np.sum(nums))
print("Maximum:", np.max(nums))
print("Minimum:", np.min(nums))
print("Standard deviation:", np.std(nums))

# Reshaping example
seq = np.arange(1, 10)
print("Before reshape:", seq)
print("After reshape:\n", seq.reshape(3, 3))


Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10
Standard deviation: 14.142135623730951
Original: [1 2 3 4 5 6 7 8 9]
Reshaped:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# ---------------- PANDAS ----------------

print("\n========== PANDAS ==========")

# Making a Series first
scores = pd.Series([85, 90, 78, 92, 88])
print("Series:\n", scores)

# Making a simple student DataFrame
student_data = {
    "Name": ["Anu", "Bharath", "Chitra", "Deepak", "Esha"],
    "Age": [20, 21, 20, 22, 21],
    "Marks": [85, 90, 78, 92, 88]
}

students = pd.DataFrame(student_data)
print("\nDataFrame:")
print(students)

# Quick look at the table
print("\nColumns:", students.columns)
print("Shape:", students.shape)

print("\nLast 2 rows:")
print(students.tail(2))
print("\nFirst 3 rows:")
print(students.head(3))

# Taking one column and one row
print("\nNames:")
print(students["Name"])
print("\nFirst row:")
print(students.iloc[0])

# Filter students with marks more than 85
print("\nMarks above 85:")
print(students[students["Marks"] > 85])

# Sorting marks from high to low
print("\nSorted by marks:")
print(students.sort_values("Marks", ascending=False))

# Getting some statistics
print("\nMarks statistics:")
print(students["Marks"].describe())

# Adding result column
students["Result"] = ["Pass", "Pass", "Pass", "Pass", "Pass"]
print("\nUpdated DataFrame:")
print(students)

# Saving it as csv file
students.to_csv("student_data.csv", index=False)
print("\nData saved to student_data.csv")
